export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_INVALID = 'AUTH_LOGIN_INVALID';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_INVALID = 'SIGNUP_INVALID';


export const AUTH_LOGOUT = 'AUTH_LOGIN_LOGOUT';

export const DASHBOARD_LOAD_MENU = 'DASHBOARD_LOAD_MENU';
